### ISSUE TITLE
Función vecino()

### ISSUE THREAD

**Issue by canek-pelaez** [karlycaramelo/HOC#1]
En tu función vecino:

https://github.com/karlycaramelo/HOC/blob/master/go/tsp.go#L262

estás haciendo un número aleatorio de intercambios: deben ser nada más 2. Básicamente elimina las líneas 270-276 y 284-285, para que nada más haga dos intercambios.

**Comment by karlycaramelo** [comment]
No hacia cambios aleatorios solo hace 1 cambio la línea

    numChanges = 1

Era para solo hacer un cambio pero igual simplifique la función quitando las lineas que comento
