### ISSUE TITLE
Borrando el vecino

### ISSUE THREAD

**Issue by canek-pelaez** [karlycaramelo/HOC#3]
En [1] haces:

```go
 var eseprima = vecino(random, ese)
 for i := 0;i < len(cities); i++ {
    ese[i] = eseprima[i]
}
```
Con eso estás reemplazando ese con eseprima (efectivamente), cuando sólo deberías hacerlo al aceptar la solución.

[1] https://github.com/karlycaramelo/HOC/blob/master/go/tsp.go#L302

**Comment by karlycaramelo** [comment]
No estaba haciendo esto correctamente cambie esa asignación a dentro de la condición

    if (efeeseprima < efeese + float64(te))

para que solo se haga cuando es aceptada
