### ISSUE TITLE
Actualizar evaluación

### ISSUE THREAD

**Issue by canek-pelaez** [karlycaramelo/HOC#4]
En [1] haces:

```go
if (efese < efenewbestCities){
    for i := 0;i < len(ese); i++ {
        newbestCities[i] = ese[i]
    }
}
```

Eso actualiza la mejor solución; pero no actualizas `efenewbestCities`, que también debes hacer.

[1] https://github.com/karlycaramelo/HOC/blob/master/go/tsp.go#L412

**Comment by karlycaramelo** [comment]
Agregue la actualización de efenewbestcities también:

            if (efese < efenewbestCities){
                for i := 0;i < len(ese); i++ {
                    newbestCities[i] = ese[i]
                }
                efenewbestCities = efese
            }
