### ISSUE TITLE
Índice contaminado

### ISSUE THREAD

**Issue by canek-pelaez** [karlycaramelo/HOC#6]
En [1] haces:

```go
func porcentajeAceptados(...) float64{
    ...
    var i = 1 
    ...
    ese = make([]city, len(cities))
    for i := 0;i < len(cities); i++ {
        ese[i] = cities[i]
    }
    ...
    for (i < int(ene)){
```

Según yo el `for` contamina la variable `i`, dejándola con el valor `len(cities) - 1`. Sólo para asegurarnos, declara `i` debajo del `for` donde la usas (eso fuerza a que la `i` del `for` sea local).

[1] https://github.com/karlycaramelo/HOC/blob/master/go/tsp.go#L292

**Comment by karlycaramelo** [comment]
Cambie mejor las i por j para evitar la posible contaminación
